# SPDX-License-Identifier: Apache-2.0
# Emit CONFIG_NOXTLS_ESP_HW_* macros for NoxTLS static libs (noxtls_pkc, etc.).
# Sub-cmake targets do not reliably see sdkconfig.h; this header is on the same
# include path as noxtls_config_features.h.

function(noxtls_esp_idf_write_hw_accel_header out_file)
  if(NOT out_file)
    message(FATAL_ERROR "noxtls_esp_idf_write_hw_accel_header: out_file required")
  endif()
  set(_h "/* Generated from ESP-IDF sdkconfig. Do not edit. */\n")
  string(APPEND _h "#ifndef NOXTLS_ESP_HW_ACCEL_H\n")
  string(APPEND _h "#define NOXTLS_ESP_HW_ACCEL_H\n\n")

  if(CONFIG_NOXTLS_ESP_HW_ECC)
    string(APPEND _h "#define CONFIG_NOXTLS_ESP_HW_ECC 1\n")
  else()
    string(APPEND _h "#define CONFIG_NOXTLS_ESP_HW_ECC 0\n")
  endif()
  if(CONFIG_NOXTLS_ESP_HW_ECDSA)
    string(APPEND _h "#define CONFIG_NOXTLS_ESP_HW_ECDSA 1\n")
  else()
    string(APPEND _h "#define CONFIG_NOXTLS_ESP_HW_ECDSA 0\n")
  endif()
  if(CONFIG_NOXTLS_ESP_HW_MPI)
    string(APPEND _h "#define CONFIG_NOXTLS_ESP_HW_MPI 1\n")
  else()
    string(APPEND _h "#define CONFIG_NOXTLS_ESP_HW_MPI 0\n")
  endif()
  if(CONFIG_NOXTLS_ESP_HW_AES)
    string(APPEND _h "#define CONFIG_NOXTLS_ESP_HW_AES 1\n")
  else()
    string(APPEND _h "#define CONFIG_NOXTLS_ESP_HW_AES 0\n")
  endif()
  if(CONFIG_NOXTLS_ESP_HW_SHA)
    string(APPEND _h "#define CONFIG_NOXTLS_ESP_HW_SHA 1\n")
  else()
    string(APPEND _h "#define CONFIG_NOXTLS_ESP_HW_SHA 0\n")
  endif()
  if(CONFIG_MBEDTLS_HARDWARE_MPI)
    string(APPEND _h "#define CONFIG_MBEDTLS_HARDWARE_MPI 1\n")
  else()
    string(APPEND _h "#define CONFIG_MBEDTLS_HARDWARE_MPI 0\n")
  endif()

  string(APPEND _h "\n#endif /* NOXTLS_ESP_HW_ACCEL_H */\n")
  file(WRITE "${out_file}" "${_h}")
endfunction()
