# SPDX-License-Identifier: Apache-2.0
# Generated from noxtls_config_catalog.xml — do not edit by hand.
# Generator: noxtls/tools/kconfig_gen/generate_kconfig.py (2026-06-01T22:10:15Z)

function(noxtls_esp_idf_write_config_features_header out_file)
  if(NOT out_file)
    message(FATAL_ERROR "noxtls_esp_idf_write_config_features_header: out_file required")
  endif()
  set(_noxtls_hdr "")
  string(APPEND _noxtls_hdr "/* Generated from ESP-IDF sdkconfig (menuconfig).\n")
  string(APPEND _noxtls_hdr " * Do not edit; regenerate via tools/kconfig_gen/generate_kconfig.py. */\n\n")
  string(APPEND _noxtls_hdr "#ifndef _NOXTLS_CONFIG_FEATURES_H_\n")
  string(APPEND _noxtls_hdr "#define _NOXTLS_CONFIG_FEATURES_H_\n\n")

if(CONFIG_NOXTLS_CFG_ENABLE_NOXSIGHT)
  string(APPEND _noxtls_hdr "#define NOXTLS_CFG_ENABLE_NOXSIGHT 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_CFG_ENABLE_NOXSIGHT 0\n")
endif()

if(CONFIG_NOXTLS_CFG_TLS13_ALLOW_RSA_PKCS1_CERTVERIFY)
  string(APPEND _noxtls_hdr "#define NOXTLS_CFG_TLS13_ALLOW_RSA_PKCS1_CERTVERIFY 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_CFG_TLS13_ALLOW_RSA_PKCS1_CERTVERIFY 0\n")
endif()

if(CONFIG_NOXTLS_CFG_TLS13_PREFER_SECP256R1_OVER_X25519)
  string(APPEND _noxtls_hdr "#define NOXTLS_CFG_TLS13_PREFER_SECP256R1_OVER_X25519 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_CFG_TLS13_PREFER_SECP256R1_OVER_X25519 0\n")
endif()

if(CONFIG_NOXTLS_CFG_TLS_ALLOW_PSK_ONLY)
  string(APPEND _noxtls_hdr "#define NOXTLS_CFG_TLS_ALLOW_PSK_ONLY 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_CFG_TLS_ALLOW_PSK_ONLY 0\n")
endif()

if(CONFIG_NOXTLS_ECC_FIXED_POINT_OPTIM)
  string(APPEND _noxtls_hdr "#define NOXTLS_ECC_FIXED_POINT_OPTIM 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_ECC_FIXED_POINT_OPTIM 0\n")
endif()

string(APPEND _noxtls_hdr "#define NOXTLS_ECC_POINT_MUL_WINDOW_SIZE ${CONFIG_NOXTLS_ECC_POINT_MUL_WINDOW_SIZE}\n")

if(CONFIG_NOXTLS_ECDSA_SIGN_SELF_VERIFY)
  string(APPEND _noxtls_hdr "#define NOXTLS_ECDSA_SIGN_SELF_VERIFY 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_ECDSA_SIGN_SELF_VERIFY 0\n")
endif()

if(NOXTLS_CFG_FEATURE_AES)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_AES 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_AES 0\n")
endif()

if(NOXTLS_CFG_FEATURE_AES_128)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_AES_128 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_AES_128 0\n")
endif()

if(NOXTLS_CFG_FEATURE_AES_192)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_AES_192 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_AES_192 0\n")
endif()

if(NOXTLS_CFG_FEATURE_AES_256)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_AES_256 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_AES_256 0\n")
endif()

if(NOXTLS_CFG_FEATURE_AES_ACCEL_APPLE)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_AES_ACCEL_APPLE 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_AES_ACCEL_APPLE 0\n")
endif()

if(NOXTLS_CFG_FEATURE_AES_ACCEL_NI)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_AES_ACCEL_NI 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_AES_ACCEL_NI 0\n")
endif()

if(NOXTLS_CFG_FEATURE_AES_CBC)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_AES_CBC 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_AES_CBC 0\n")
endif()

if(NOXTLS_CFG_FEATURE_AES_CCM)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_AES_CCM 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_AES_CCM 0\n")
endif()

if(NOXTLS_CFG_FEATURE_AES_CFB)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_AES_CFB 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_AES_CFB 0\n")
endif()

if(NOXTLS_CFG_FEATURE_AES_CMAC)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_AES_CMAC 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_AES_CMAC 0\n")
endif()

if(NOXTLS_CFG_FEATURE_AES_CTR)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_AES_CTR 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_AES_CTR 0\n")
endif()

if(NOXTLS_CFG_FEATURE_AES_ECB)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_AES_ECB 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_AES_ECB 0\n")
endif()

if(NOXTLS_CFG_FEATURE_AES_GCM)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_AES_GCM 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_AES_GCM 0\n")
endif()

if(NOXTLS_CFG_FEATURE_AES_OFB)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_AES_OFB 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_AES_OFB 0\n")
endif()

if(NOXTLS_CFG_FEATURE_AES_XTS)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_AES_XTS 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_AES_XTS 0\n")
endif()

if(NOXTLS_CFG_FEATURE_ARIA)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_ARIA 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_ARIA 0\n")
endif()

if(NOXTLS_CFG_FEATURE_BLAKE2)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_BLAKE2 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_BLAKE2 0\n")
endif()

if(NOXTLS_CFG_FEATURE_CAMELLIA)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_CAMELLIA 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_CAMELLIA 0\n")
endif()

if(NOXTLS_CFG_FEATURE_CERT)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_CERT 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_CERT 0\n")
endif()

if(NOXTLS_CFG_FEATURE_CHACHA20_POLY1305)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_CHACHA20_POLY1305 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_CHACHA20_POLY1305 0\n")
endif()

if(NOXTLS_CFG_FEATURE_DES)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_DES 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_DES 0\n")
endif()

if(NOXTLS_CFG_FEATURE_DH)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_DH 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_DH 0\n")
endif()

if(NOXTLS_CFG_FEATURE_DRBG)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_DRBG 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_DRBG 0\n")
endif()

if(NOXTLS_CFG_FEATURE_DSA)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_DSA 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_DSA 0\n")
endif()

if(NOXTLS_CFG_FEATURE_DTLS)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_DTLS 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_DTLS 0\n")
endif()

if(NOXTLS_CFG_FEATURE_ECC)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_ECC 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_ECC 0\n")
endif()

if(NOXTLS_CFG_FEATURE_ECDH)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_ECDH 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_ECDH 0\n")
endif()

if(NOXTLS_CFG_FEATURE_ECDSA)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_ECDSA 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_ECDSA 0\n")
endif()

if(NOXTLS_CFG_FEATURE_ED25519)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_ED25519 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_ED25519 0\n")
endif()

if(NOXTLS_CFG_FEATURE_ED448)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_ED448 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_ED448 0\n")
endif()

if(NOXTLS_CFG_FEATURE_ENCRYPTION)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_ENCRYPTION 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_ENCRYPTION 0\n")
endif()

if(CONFIG_NOXTLS_FEATURE_FALCON)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_FALCON 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_FALCON 0\n")
endif()

if(NOXTLS_CFG_FEATURE_HASH)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_HASH 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_HASH 0\n")
endif()

if(CONFIG_NOXTLS_FEATURE_LMS_HSS)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_LMS_HSS 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_LMS_HSS 0\n")
endif()

if(NOXTLS_CFG_FEATURE_MD4)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_MD4 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_MD4 0\n")
endif()

if(NOXTLS_CFG_FEATURE_MD5)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_MD5 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_MD5 0\n")
endif()

if(NOXTLS_CFG_FEATURE_ML_DSA)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_ML_DSA 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_ML_DSA 0\n")
endif()

if(NOXTLS_CFG_FEATURE_ML_KEM)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_ML_KEM 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_ML_KEM 0\n")
endif()

if(NOXTLS_CFG_FEATURE_PKC)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_PKC 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_PKC 0\n")
endif()

if(NOXTLS_CFG_FEATURE_RC4)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_RC4 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_RC4 0\n")
endif()

if(NOXTLS_CFG_FEATURE_RIPEMD160)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_RIPEMD160 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_RIPEMD160 0\n")
endif()

if(NOXTLS_CFG_FEATURE_RSA)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_RSA 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_RSA 0\n")
endif()

if(NOXTLS_CFG_FEATURE_SHA1)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_SHA1 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_SHA1 0\n")
endif()

if(NOXTLS_CFG_FEATURE_SHA224)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_SHA224 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_SHA224 0\n")
endif()

if(NOXTLS_CFG_FEATURE_SHA256)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_SHA256 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_SHA256 0\n")
endif()

if(NOXTLS_CFG_FEATURE_SHA3)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_SHA3 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_SHA3 0\n")
endif()

if(NOXTLS_CFG_FEATURE_SHA384)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_SHA384 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_SHA384 0\n")
endif()

if(NOXTLS_CFG_FEATURE_SHA512)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_SHA512 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_SHA512 0\n")
endif()

if(NOXTLS_CFG_FEATURE_SLH_DSA)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_SLH_DSA 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_SLH_DSA 0\n")
endif()

if(NOXTLS_CFG_FEATURE_TLS)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_TLS 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_TLS 0\n")
endif()

if(NOXTLS_CFG_FEATURE_TLS10)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_TLS10 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_TLS10 0\n")
endif()

if(NOXTLS_CFG_FEATURE_TLS11)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_TLS11 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_TLS11 0\n")
endif()

if(NOXTLS_CFG_FEATURE_TLS12)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_TLS12 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_TLS12 0\n")
endif()

if(NOXTLS_CFG_FEATURE_TLS13)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_TLS13 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_TLS13 0\n")
endif()

if(NOXTLS_CFG_FEATURE_X25519)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_X25519 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_X25519 0\n")
endif()

if(NOXTLS_CFG_FEATURE_X448)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_X448 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_X448 0\n")
endif()

if(CONFIG_NOXTLS_FEATURE_XMSS)
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_XMSS 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_FEATURE_XMSS 0\n")
endif()

if(NOXTLS_CFG_HAVE_CERT_WRITE)
  string(APPEND _noxtls_hdr "#define NOXTLS_HAVE_CERT_WRITE 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_HAVE_CERT_WRITE 0\n")
endif()

if(CONFIG_NOXTLS_HAVE_TIME)
  string(APPEND _noxtls_hdr "#define NOXTLS_HAVE_TIME 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_HAVE_TIME 0\n")
endif()

string(APPEND _noxtls_hdr "#define NOXTLS_MAX_CERT_CHAIN_DEPTH ${CONFIG_NOXTLS_MAX_CERT_CHAIN_DEPTH}\n")

string(APPEND _noxtls_hdr "#define NOXTLS_MAX_CERT_SIZE ${CONFIG_NOXTLS_MAX_CERT_SIZE}\n")

string(APPEND _noxtls_hdr "#define NOXTLS_RSA_DEBUG_PRIMALITY_CHECK_INTERVAL ${CONFIG_NOXTLS_RSA_DEBUG_PRIMALITY_CHECK_INTERVAL}\n")

string(APPEND _noxtls_hdr "#define NOXTLS_RSA_DEBUG_PROGRESS_INTERVAL ${CONFIG_NOXTLS_RSA_DEBUG_PROGRESS_INTERVAL}\n")

string(APPEND _noxtls_hdr "#define NOXTLS_RSA_DEBUG_REJECTED_CANDIDATE_INTERVAL ${CONFIG_NOXTLS_RSA_DEBUG_REJECTED_CANDIDATE_INTERVAL}\n")

string(APPEND _noxtls_hdr "#define NOXTLS_RSA_DEBUG_REJECTED_CANDIDATE_MAX_ATTEMPTS ${CONFIG_NOXTLS_RSA_DEBUG_REJECTED_CANDIDATE_MAX_ATTEMPTS}\n")

if(CONFIG_NOXTLS_RSA_ENABLE_QUICK_DIVISIBILITY_TEST)
  string(APPEND _noxtls_hdr "#define NOXTLS_RSA_ENABLE_QUICK_DIVISIBILITY_TEST 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_RSA_ENABLE_QUICK_DIVISIBILITY_TEST 0\n")
endif()

string(APPEND _noxtls_hdr "#define NOXTLS_RSA_MAX_PRIME_ATTEMPTS ${CONFIG_NOXTLS_RSA_MAX_PRIME_ATTEMPTS}\n")

string(APPEND _noxtls_hdr "#define NOXTLS_RSA_MILLER_RABIN_ITERATIONS_LARGE ${CONFIG_NOXTLS_RSA_MILLER_RABIN_ITERATIONS_LARGE}\n")

string(APPEND _noxtls_hdr "#define NOXTLS_RSA_MILLER_RABIN_ITERATIONS_SMALL ${CONFIG_NOXTLS_RSA_MILLER_RABIN_ITERATIONS_SMALL}\n")

string(APPEND _noxtls_hdr "#define NOXTLS_RSA_MILLER_RABIN_SMALL_THRESHOLD_BITS ${CONFIG_NOXTLS_RSA_MILLER_RABIN_SMALL_THRESHOLD_BITS}\n")

string(APPEND _noxtls_hdr "#define NOXTLS_STATIC_BUFFER_SIZE ${CONFIG_NOXTLS_STATIC_BUFFER_SIZE}\n")

if(NOXTLS_CFG_TLS12_ENABLE_LEGACY_CIPHER_SUITES)
  string(APPEND _noxtls_hdr "#define NOXTLS_TLS12_ENABLE_LEGACY_CIPHER_SUITES 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_TLS12_ENABLE_LEGACY_CIPHER_SUITES 0\n")
endif()

string(APPEND _noxtls_hdr "#define NOXTLS_TLS_MAX_HANDSHAKE_SIZE ${CONFIG_NOXTLS_TLS_MAX_HANDSHAKE_SIZE}\n")

string(APPEND _noxtls_hdr "#define NOXTLS_TLS_MAX_RECORD_SIZE ${CONFIG_NOXTLS_TLS_MAX_RECORD_SIZE}\n")

string(APPEND _noxtls_hdr "#define NOXTLS_TLS_MAX_WIRE_RECORD_LENGTH ${CONFIG_NOXTLS_TLS_MAX_WIRE_RECORD_LENGTH}\n")

if(CONFIG_NOXTLS_USE_STATIC_BUFFERS)
  string(APPEND _noxtls_hdr "#define NOXTLS_USE_STATIC_BUFFERS 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_USE_STATIC_BUFFERS 0\n")
endif()

if(CONFIG_NOXTLS_X509_HOSTNAME_ALLOW_WILDCARD)
  string(APPEND _noxtls_hdr "#define NOXTLS_X509_HOSTNAME_ALLOW_WILDCARD 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_X509_HOSTNAME_ALLOW_WILDCARD 0\n")
endif()

if(CONFIG_NOXTLS_SIDECHANNEL_PERFORMANCE)
  string(APPEND _noxtls_hdr "#define NOXTLS_SIDECHANNEL_PROFILE_PERFORMANCE 1\n")
  string(APPEND _noxtls_hdr "#define NOXTLS_CT_COMPARE 0\n")
elseif(CONFIG_NOXTLS_SIDECHANNEL_CONSTANT_TIME_STRICT)
  string(APPEND _noxtls_hdr "#define NOXTLS_SIDECHANNEL_PROFILE_CONSTANT_TIME_STRICT 1\n")
  string(APPEND _noxtls_hdr "#define NOXTLS_CT_COMPARE 1\n")
else()
  string(APPEND _noxtls_hdr "#define NOXTLS_SIDECHANNEL_PROFILE_BALANCED 1\n")
  string(APPEND _noxtls_hdr "#define NOXTLS_CT_COMPARE 1\n")
endif()
if(CONFIG_NOXTLS_PROFILE_MINIMAL_TLS_CLIENT)
  string(APPEND _noxtls_hdr "#define NOXTLS_PROFILE_MINIMAL_TLS_CLIENT 1\n")
endif()
if(CONFIG_NOXTLS_PROFILE_TLS_SERVER_PKI)
  string(APPEND _noxtls_hdr "#define NOXTLS_PROFILE_TLS_SERVER_PKI 1\n")
endif()
if(CONFIG_NOXTLS_PROFILE_CRYPTO_ONLY)
  string(APPEND _noxtls_hdr "#define NOXTLS_PROFILE_CRYPTO_ONLY 1\n")
endif()
if(CONFIG_NOXTLS_PROFILE_FIPS_LIKE)
  string(APPEND _noxtls_hdr "#define NOXTLS_PROFILE_FIPS_LIKE 1\n")
endif()

  string(APPEND _noxtls_hdr "\n#endif /* _NOXTLS_CONFIG_FEATURES_H_ */\n")
  file(WRITE "${out_file}" "${_noxtls_hdr}")
endfunction()
