set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES ARM_GNU_TOOLCHAIN_ROOT)

set(ARM_GNU_TOOLCHAIN_ROOT "" CACHE PATH "Root of ARM GNU toolchain installation")
if(NOT ARM_GNU_TOOLCHAIN_ROOT AND DEFINED ENV{ARM_GNU_TOOLCHAIN_ROOT})
    set(ARM_GNU_TOOLCHAIN_ROOT "$ENV{ARM_GNU_TOOLCHAIN_ROOT}")
endif()

if(ARM_GNU_TOOLCHAIN_ROOT)
    set(_arm_search_path "${ARM_GNU_TOOLCHAIN_ROOT}/bin")
    find_program(_ARM_GCC arm-none-eabi-gcc HINTS "${_arm_search_path}" REQUIRED NO_DEFAULT_PATH)
    find_program(_ARM_GXX arm-none-eabi-g++ HINTS "${_arm_search_path}" NO_DEFAULT_PATH)
    find_program(_ARM_OBJDUMP arm-none-eabi-objdump HINTS "${_arm_search_path}" REQUIRED NO_DEFAULT_PATH)
    find_program(_ARM_SIZE arm-none-eabi-size HINTS "${_arm_search_path}" REQUIRED NO_DEFAULT_PATH)
else()
    find_program(_ARM_GCC arm-none-eabi-gcc REQUIRED)
    find_program(_ARM_GXX arm-none-eabi-g++)
    find_program(_ARM_OBJDUMP arm-none-eabi-objdump REQUIRED)
    find_program(_ARM_SIZE arm-none-eabi-size REQUIRED)
endif()

set(CMAKE_C_COMPILER "${_ARM_GCC}" CACHE FILEPATH "" FORCE)
set(CMAKE_ASM_COMPILER "${_ARM_GCC}" CACHE FILEPATH "" FORCE)
if(_ARM_GXX)
    set(CMAKE_CXX_COMPILER "${_ARM_GXX}" CACHE FILEPATH "" FORCE)
endif()
set(CMAKE_OBJDUMP "${_ARM_OBJDUMP}" CACHE FILEPATH "" FORCE)
set(CMAKE_SIZE "${_ARM_SIZE}" CACHE FILEPATH "" FORCE)
