#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later OR NoxTLS-Commercial
# Copyright (c) [2019] - [2026], Argenox Technologies LLC
"""
Regenerate the BA414EP microcode word array used by the nRF54L15 CRACEN backend
(noxtls-lib/vendor/nordic/nrf54x/noxtls_nrf54_ba414ep_ucode.c) from the raw
image noxtls-lib/vendor/nordic/nrf54x/ucode/ba414ep_ucode.bin.

The image is a sequence of little-endian 32-bit words, in the order they are
written to the PKE microcode RAM (CRACENCORE + 0xC000). It is only needed on
the nRF54L15: the nRF54LM20 (CRACEN Lite) executes its microcode from ROM.

Usage:
  python gen_ba414ep_ucode.py            # write the C array
  python gen_ba414ep_ucode.py --check    # fail if the C array does not match the image
"""

from __future__ import annotations

import argparse
import hashlib
import re
import struct
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
NOXTLS_ROOT = SCRIPT_DIR.parent.parent
BIN_PATH = NOXTLS_ROOT / "noxtls-lib" / "vendor" / "nordic" / "nrf54x" / "ucode" / "ba414ep_ucode.bin"
C_PATH = NOXTLS_ROOT / "noxtls-lib" / "vendor" / "nordic" / "nrf54x" / "noxtls_nrf54_ba414ep_ucode.c"
H_PATH = NOXTLS_ROOT / "noxtls-lib" / "vendor" / "nordic" / "nrf54x" / "noxtls_nrf54_ba414ep_ucode.h"
WORDS_PER_LINE = 6
WORD_BYTES = 4
# Microcode RAM of the nRF54L15 PKE (bytes).
CODE_RAM_BYTES = 5120

HEADER = """/*****************************************************************************
* Copyright (c) [2019] - [2026], Argenox Technologies LLC
* All rights reserved.
* SPDX-License-Identifier: GPL-2.0-or-later OR NoxTLS-Commercial
*
*
* This file is part of the NoxTLS Library.
*
* Licensed under the GNU General Public License v2.0 or later,
* or alternatively under a commercial license from
* Argenox Technologies LLC.
*
* See the LICENSE file in the project root for full details.
* CONTACT: info@argenox.com
*
*
* File:    noxtls_nrf54_ba414ep_ucode.c
* Summary: BA414EP microcode image (data only) for the nRF54L15 PKE
*
*****************************************************************************/

/**
 * @file noxtls_nrf54_ba414ep_ucode.c
 * @brief BA414EP public-key engine microcode, loaded into the nRF54L15 PKE code RAM.
 * @ingroup noxtls_nrf54
 *
 * GENERATED by tools/ba414ep_ucode/gen_ba414ep_ucode.py from
 * noxtls-lib/vendor/nordic/nrf54x/ucode/ba414ep_ucode.bin - do not edit.
 *
 * Origin of the image: the BA414EP microcode that Nordic Semiconductor
 * distributes for the nRF54L15 CRACEN in nRF Connect SDK (sdk-nrf
 * subsys/nrf_security/src/drivers/cracen, "microcode_binary.h", 2024 image;
 * identical in sdk-nrf v3.4.1 and in the main branch at version 3.4.99,
 * checked 2026-09-04 and 2026-10-05). Only the word values are reproduced;
 * no source code accompanies them. The nRF54LM20 (CRACEN Lite) runs its
 * microcode from ROM and never uses this table.
 *
 * Image: {words} words ({nbytes} bytes), SHA-256 of the little-endian image
 * {sha256}.
 */

#include <stdint.h>

#include "noxtls_nrf54_ba414ep_ucode.h"

"""


def load_words(path: Path) -> list[int]:
    data = path.read_bytes()
    if len(data) == 0 or len(data) % WORD_BYTES != 0:
        raise ValueError(f"{path}: size {len(data)} is not a non-zero multiple of {WORD_BYTES}")
    if len(data) > CODE_RAM_BYTES:
        raise ValueError(f"{path}: {len(data)} bytes exceed the {CODE_RAM_BYTES}-byte microcode RAM")
    return [w for (w,) in struct.iter_unpack("<I", data)]


def render(words: list[int], sha256: str) -> str:
    out = [HEADER.format(words=len(words), nbytes=len(words) * WORD_BYTES, sha256=sha256)]
    out.append("const uint32_t noxtls_nrf54_ba414ep_ucode[NOXTLS_NRF54_BA414EP_UCODE_WORDS] = {\n")
    for i in range(0, len(words), WORDS_PER_LINE):
        chunk = words[i:i + WORDS_PER_LINE]
        out.append("    " + ", ".join(f"0x{w:08X}u" for w in chunk) + ",\n")
    out.append("};\n")
    return "".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="verify the generated file instead of writing it")
    args = parser.parse_args()

    words = load_words(BIN_PATH)
    m = re.search(r"#define NOXTLS_NRF54_BA414EP_UCODE_WORDS (\d+)U", H_PATH.read_text(encoding="utf-8"))
    if (m is None) or (int(m.group(1)) != len(words)):
        print(f"{H_PATH}: NOXTLS_NRF54_BA414EP_UCODE_WORDS must be {len(words)}", file=sys.stderr)
        return 1
    sha256 = hashlib.sha256(BIN_PATH.read_bytes()).hexdigest()
    text = render(words, sha256)
    if args.check:
        current = C_PATH.read_text(encoding="utf-8") if C_PATH.exists() else ""
        if current != text:
            print(f"{C_PATH} is out of date; run {Path(__file__).name}", file=sys.stderr)
            return 1
        print(f"OK: {len(words)} words, sha256 {sha256}")
        return 0
    C_PATH.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {C_PATH} ({len(words)} words, sha256 {sha256})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
