macro(_noxtls_size_set_bool var value)
    set(${var} ${value})
    set(${var} ${value} CACHE BOOL "" FORCE)
endmacro()

macro(_noxtls_size_set_profile value)
    set(NOXTLS_PROFILE ${value})
    set(NOXTLS_PROFILE ${value} CACHE STRING "NoxTLS benchmark profile" FORCE)
endmacro()

macro(noxtls_apply_size_profile profile_name)
    string(TOLOWER "${profile_name}" _profile)

    if(_profile STREQUAL "crypto_only")
        _noxtls_size_set_profile("crypto_only")
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_CERT OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_TLS OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_TLS12 OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_TLS13 OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_DTLS OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_ML_KEM OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_ML_DSA OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_SLH_DSA OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_FALCON OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_LMS_HSS OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_XMSS OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_HAVE_CERT_WRITE OFF)
    elseif(_profile STREQUAL "tls12_only")
        _noxtls_size_set_profile("default")
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_CERT ON)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_TLS ON)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_TLS12 ON)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_TLS13 OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_DTLS OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_ML_KEM OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_ML_DSA OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_SLH_DSA OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_FALCON OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_LMS_HSS OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_XMSS OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_HAVE_CERT_WRITE ON)
    elseif(_profile STREQUAL "tls13_only")
        _noxtls_size_set_profile("default")
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_CERT ON)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_TLS ON)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_TLS12 OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_TLS13 ON)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_DTLS OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_ML_KEM OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_ML_DSA OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_SLH_DSA OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_FALCON OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_LMS_HSS OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_XMSS OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_HAVE_CERT_WRITE ON)
    elseif(_profile STREQUAL "tls12_tls13")
        _noxtls_size_set_profile("default")
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_CERT ON)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_TLS ON)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_TLS12 ON)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_TLS13 ON)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_DTLS OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_ML_KEM OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_ML_DSA OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_SLH_DSA OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_FALCON OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_LMS_HSS OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_XMSS OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_HAVE_CERT_WRITE ON)
    elseif(_profile STREQUAL "full_quantum")
        _noxtls_size_set_profile("default")
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_CERT ON)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_TLS ON)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_TLS12 ON)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_TLS13 ON)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_DTLS OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_ML_KEM ON)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_ML_DSA ON)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_SLH_DSA ON)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_FALCON OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_LMS_HSS OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_FEATURE_XMSS OFF)
        _noxtls_size_set_bool(NOXTLS_CFG_HAVE_CERT_WRITE ON)
    else()
        message(FATAL_ERROR
            "Unsupported NOXTLS_SIZE_PROFILE='${profile_name}'. "
            "Expected: crypto_only, tls12_only, tls13_only, tls12_tls13, full_quantum."
        )
    endif()
endmacro()
